import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Nextjs-Markdown-tailwindcss</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className='min-h-screen bg-gray-200 flex items-center justify-center'>
        <p className='inline-block  text-3xl font-mono font-semibold'>Hello Nextjs with tailwindcss</p>
      </main>
    </>
  );
}
